apiVersion: vra8.vmware.vra/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: vra-creds
      namespace: default
      key: credentials
