// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AccountAws) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountAzure) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountGCP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountNsxt) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountVmc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AccountVsphere) Hub() {}
